/*
 *  D bindings for Dynamic Linking Generator
 *  Copyright (c) 2013, Okuno Zankoku
 *  All rights reserved. 
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this 
 *  list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *  this list of conditions and the following disclaimer in the documentation
 *  and/or other materials provided with the distribution.
 *
 *  Neither the name of Okuno Zankoku nor the names of contributors may be used
 *  to endorse or promote products derived from this software without specific
 *  prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY Okuo Zankoku "AS IS" AND ANY EXPRESS OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 *  EVENT SHALL {{THE COPYRIGHT HOLDER OR CONTRIBUTORS}} BE LIABLE FOR ANY
 *  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 *  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 *  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


const char* constants = "\
enum {\n\
  RTLD_LOCAL = %d,\n\
  RTLD_GLOBAL = %d,\n\
  RTLD_LAZY = %d,\n\
  RTLD_NOW = %d\n\
}\n\
";

const char* functions = "\
void* dlopen(immutable char* file, int mode);\n\
int dlclose (void* handle);\n\
void* dlsym (const void* handle, immutable char* name);\n\
char* dlerror ();\n\
";

const char* header = "\
/*\n\
 *  D bindings for dlfcn.h generated by 'D bindings for Dynamic Linking\n\
 *  Generator'.\n\
 *\n\
 *  If you experience any problems with this file, please contact Okuno Zankoku\n\
 *  at <zankoku.okuno@gmail.com>. Include any information necessary to reproduce\n\
 *  the error, including your system information, and any fixes to \n\
 *  'config-dlfcn.c' that you were able to make.\n\
 */\n\
";

const char* prologue = "\
module dlfcn;\n\
\n\
public:\n\
extern (C) {\n\
";

const char* epilogue = "\
} /* extern (C) */\n\
";

#include <stdlib.h>
#include <stdio.h>
#include <dlfcn.h>

int main(int argc, char** argv) {
	if (argc > 1)
		fprintf(stderr, "[WARNING] Command-line arguments ignored\n");

	puts(header);
	puts(prologue);
	printf(constants, RTLD_LOCAL, RTLD_GLOBAL, RTLD_LAZY, RTLD_NOW);
	puts(functions);
	puts(epilogue);
	exit(0);
}